In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])

In [3]:
array2=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

In [4]:
array3=np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [1,3,5,7,9]
],
               [
                   [6,5,4,3,2],
                   [1,6,9,1,4],
                   [22,33,44,55,66]
               ]])

In [5]:
array1.ndim

1

In [7]:
array2.ndim

2

In [9]:
array3.ndim

3

In [10]:
array1.shape

(5,)

In [11]:
array2.shape

(3, 5)

In [12]:
array3.shape

(2, 3, 5)

In [13]:
array1.size

5

In [14]:
array2.size

15

In [15]:
array3.size

30

In [16]:
array1.dtype

dtype('int32')

In [17]:
array1[0]

1

In [18]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
array2[1][2]

8

In [21]:
array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  3,  5,  7,  9]],

       [[ 6,  5,  4,  3,  2],
        [ 1,  6,  9,  1,  4],
        [22, 33, 44, 55, 66]]])

In [22]:
array3[1][0][3]

3

In [23]:
array2[1,2]

8

In [24]:
array3[1,0,3]

3

In [25]:
array2[1,1]*array3[1,2,3]

385

In [31]:
print(array2)
print("----------")
print(array2*2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [33]:
print(array1)
print("___________________")
print(array2)

[1 2 3 4 5]
___________________
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
print(array1*array2)

[[ 1  4  9 16 25]
 [ 6 14 24 36 50]
 [11 24 39 56 75]]


In [37]:
np.sum(array3)

341

In [41]:
np.product(array1)

120

In [42]:
array1

array([1, 2, 3, 4, 5])

In [45]:
array11=np.zeros((3,4))

In [46]:
array11

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
array11[1,2]=25

In [49]:
array11

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [50]:
array11[2,3]=36

In [51]:
array11

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0., 36.]])

In [52]:
np.sum(array11)

61.0

In [53]:
np.product(array11)

0.0

In [55]:
array22=np.ones((3,5))

In [56]:
array22[2,1]=25

In [57]:
array22[1,2]=36

In [59]:
np.product(array22)

900.0

In [60]:
36*25

900

In [61]:
list1=[33,44,55,65,69]

In [62]:
array4=np.array(list1)

In [63]:
array4

array([33, 44, 55, 65, 69])

In [64]:
list2=['king', 'ring',2,3,4,'rose']

In [69]:
array5=np.array(list2)

In [71]:
array5

array(['king', 'ring', '2', '3', '4', 'rose'], dtype='<U11')

In [79]:
value=int(array5[11])

IndexError: index 11 is out of bounds for axis 0 with size 6

In [77]:
type(value)

int

In [84]:
try:
    idx=int(input('enter index'))
    try:
        value=int(array5[idx])
        print(value)
    except ValueError:
        pass
except ValueError:
    value=array5[idx]
    print(value)
except IndexError:
    print('enter proper index')

enter index 2


2


In [89]:
try:
    value = int(input("Enter index: "))
    try:
        print(int(array5[value]))
    except ValueError:
        print(array5[value])

except ValueError:
    print("Index must be a number")

except IndexError:
    print("Index out of range")


Enter index:  3


3


In [92]:
nums=[]
for i in list2:
    try:
        nums.append(float(i))
    except:
        pass

In [93]:
nums

[2.0, 3.0, 4.0]

In [94]:
list3=['1e3', 'NaN', 'inf', '3', '4']

In [95]:
nums2=[]

In [97]:
for i in list3:
    try:
        nums2.append(float(i))
    except:
        pass

In [99]:
nums3=[]

In [107]:
for i in list3:
    try:
        val=float(i)
        if not (val==float('1e3') or val==float('inf') or val==float('-inf') or val!=val):
            nums3.append(val)
    except:
        pass

In [108]:
nums3

[3.0, 4.0]

In [111]:
array6=np.array([1,2,3,4,5,65,67,7,8,9,11,22,33,44,55,66,77,22])

In [112]:
array6.size

18

In [113]:
array6.reshape(3,6)

array([[ 1,  2,  3,  4,  5, 65],
       [67,  7,  8,  9, 11, 22],
       [33, 44, 55, 66, 77, 22]])

In [114]:
array6.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5, 65],
        [67,  7,  8]],

       [[ 9, 11, 22],
        [33, 44, 55],
        [66, 77, 22]]])

In [115]:
array7=np.ones((5,7,9))

In [137]:
array8=np.array([1,3,4,5,6,7,8])

In [138]:
array8.size

7

In [139]:
array8.resize(2,25)

In [140]:
array8

array([[1, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [143]:
array8(50)

TypeError: 'numpy.ndarray' object is not callable

In [146]:
np.max(array2)

15

In [147]:
np.argmax(array2)

14

In [148]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [150]:
array2.argmax()

14

In [152]:
array2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [155]:
np.max(array2, axis=1)

array([ 5, 10, 15])

In [156]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [157]:
np.max(array2, axis=0)

array([11, 12, 13, 14, 15])

In [158]:
np.sum(array2, axis=1)

array([15, 40, 65])

In [159]:
np.sum(array2, axis=0)

array([18, 21, 24, 27, 30])

In [160]:
array1

array([1, 2, 3, 4, 5])

In [163]:
np.sum(array1, axis=0)

15

In [164]:
array9=np.ones(20)

In [165]:
array9

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [166]:
np.resize(array9, (10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [167]:
np.resize(array9, (50))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
array10=np.ones(10)

In [169]:
array10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [174]:
array10=np.resize(array10, (4,7))

In [175]:
array10

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [176]:
np.resize(array10, (50))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [177]:
expenses=np.array([
    [200, 340, 230, 150, 456], #food
    [100, 345, 122, 600, 233], #travel
    [350, 450, 256, 800, 654]  #shopping
])

In [178]:
print('total expense: ', np.sum(expenses))
print('category wise sum: ', np.sum(expenses, axis=1))
print('day wise total: ', np.sum(expenses, axis=0))
print('highest expense day: ', np.max(np.sum(expenses, axis=0)))

total expense:  5286
category wise sum:  [1376 1400 2510]
day wise total:  [ 650 1135  608 1550 1343]
highest expense day:  1550


In [179]:
marks=np.array([34,56,65,78,87,65,66])

In [187]:
grades=np.where(marks>=75, "A",
        np.where(marks>=55,"B",
        np.where(marks>=40, "c", "fail")))

In [188]:
print(grades)

['fail' 'B' 'B' 'A' 'A' 'B' 'B']


In [189]:
grades=np.where(marks>=75, "A",
        np.where(marks>=60, "B",
        np.where(marks>=40, "C", "fail")))

In [190]:
grades

array(['fail', 'C', 'B', 'A', 'A', 'B', 'B'], dtype='<U4')

In [191]:
marks

array([34, 56, 65, 78, 87, 65, 66])

In [192]:
print(marks>60)

[False False  True  True  True  True  True]


In [195]:
print(marks[(marks>60) & (marks<80)])

[65 78 65 66]


In [196]:
np.mean(marks)

64.42857142857143

In [197]:
np.median(marks)

65.0

In [199]:
np.std(marks)

15.55503724436137

In [200]:
check=np.ones(20)

In [205]:
np.std(check)

435.6605329841114

In [204]:
check[5]=2000

In [207]:
arr=np.array([1,2,3,4])

In [208]:
%timeit arr*2

1.78 μs ± 603 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [209]:
%timeit [i*2 for i in arr]

1.91 μs ± 562 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [210]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [211]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [212]:
np.square(arr)

array([ 1,  4,  9, 16])

In [213]:
np.split(arr,2)

[array([1, 2]), array([3, 4])]